matrix:
  include:
    - language: java
      jdk: oraclejdk8
      dist: trusty
      before_install: cd restful-web-services/
      install: mvn install
      script: mvn test -B

    - language: node_js
      node_js:
        - 10.16.3
      sudo: required
      services:
          - xvfb
      addons:
        chrome: stable
      before_install:
        # starting a GUI to run tests, per https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
        - sudo apt-get install g++ build-essential
        - "export DISPLAY=:99.0"
        - "npm config set spin false"
      before_script:
        - "cd frontend/app"
        - "rm -rf node_modules"
        - sudo apt-get update
        - sudo apt-get install -y libappindicator1 fonts-liberation
        - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        - sudo dpkg -i google-chrome*.deb
        - "yarn install"
        - "cd .. && cd .. && ls"
        - "cd restful-web-services"
        - travis_wait 30 nohup mvn spring-boot:run &
      script: 
        - "cd .."
        - "cd frontend/app"
        - "npm rebuild node-sass"
        - "nohup npm start &"
        - sleep 5
        - "npm run test"
        - "npm run wdio"

notifications:
  slack: tomyumsept:PvqV1oTyYrS9OKT0hp2kH4TA
  email: false
